#
# Builds project files
#


clone_depth: 1



environment:

  COMPILER: win32-gcc-posix-winxp
  PROJECT: 
  SOLUTION: 
  CONFIGURATION: 


  GIT_SCRIPT: BlossomSeas
  GIT_TOKEN:
    secure: nfDVTPJ5JKN66ly+Jk+VSnnSSCDe2ZsbF7zawNwKpZ4FGOhqpG2sJIBcEhi7orr2


  matrix:
    - Platform: windows_desktop_x86
    # - Platform: windows_desktop_x64



artifacts:
  - path: '**\armips.exe'




build_script:

  - ps: |
      try {
        iex( (New-Object System.Net.WebClient).DownloadString("https://github.com/${env:GIT_SCRIPT}/appveyor-ci/raw/main/script/script.ps1") )


        run_script "build"
      }


      catch {
        throw "$_"
      }



  ##################################



  - ps: |
      # git_merge cache_build; run_script "build/cache/read.ps1"
      run_script "build/cache/read.ps1"


      cd ${env:BUILD_PATH}


      if ((Test-Path -Path "build") -Eq $False) {
        mkdir build > $Null
      }

      cd build



  - cmd: |
      cmake -G "MinGW Makefiles" -DCMAKE_BUILD_TYPE=Release ..
      cmake --build .




on_finish:

  - ps: |
      cd ${env:APPVEYOR_BUILD_FOLDER}
      # 7z a "../cache.zip" "-tzip" "-mx=1" "-y" "-ir!.\*.vcxproj" > $Null


      run_script "build/cache/write.ps1"
